### ISSUE TITLE
The Resources Pack Cannot Load

### ISSUE THREAD

**Issue by Hu1est** [FMarquesPTO/Java-Exp#1]
**Describe the bug**
Cannot load.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Global Resources'
3. See error

**Expected behavior**
Can load.

**Screenshots**
https://kyun.ltyuanfang.cn/tc/2020/10/30/4b45fcc20de12.png

**Device (please complete the following information):**
 - OS: iPadOS 13.5.1

**Additional context**
As far as I know, JSON files don't support this kind of annotation like /**/

**Comment by KalmeMarq** [comment]
JSON doesn't support comments. However, Bedrock ignores them. I already know what the error is but thanks for reporting it.
